language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy
- pypy3
install:
- pip install -r requirements.txt
- pip install requests_mock
- pip install codecov
- python setup.py -q install
script:
- nosetests -v --with-coverage
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist
  user: "peshay"
  password:
    secure: MuulvcKnhSa6YD1Vx4AM9VAHsf2n9Ks2zIwyV1hk0emhzpghrCc2uGrahMji3viQcZe28eZ3PmPSc+WhS+ZNlQ68xOuRFjks8KjdrNdSTKXFx3OOo9lBCpOwP87U2jisphTAlgmO6gCfeIQlEhiGaWR2qkEyKRZa1Sr7bxHKP0w13QyaneeUJ1f/KzXIUPk9GkZM342LsV3OyakN28mIp5nk7ea+DghEqnHqWqiy0jIiC4rDQZf10QJaRK4SIKEf62nOVdxQSYaWWyCIW9c2QcJ1xGKrZOhATJmnB8HGr26GdNkVGahM6ww2kXys21bo0U1axnzYkYMgMmgrk2qZrswEItqN9GxNrfujwhFrt9+cG6nleyC5FCmc8SUpnDqi7ILqoG71+pfKuquX81s23re3PSiqJzrPopVV+qnybVwTbetxzr0y1elxmc02AfHCRoY+7S3ZItEDdu5yS4kzGbSVR+yYDeDOtSc/gukhEHAc9XiVPX3ixQaztyNwaXM5tvFVF1Uhm937YUzSUffpvVrZLV/jobmlBfIYU406CMTFdo9F8IbUZz5rtlRgK9EN6NAVi+VZA2Orzxg3FVg6TmaNzb0OwZ5Hk8+a69H/0dzuXBgcFDONgVRfwht0Kp8WgdtAcoqSdCmerFUCroi0XPh28/y7a0ursD0nAh7glz0=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
notifications:
  email:
    recipients:
      - anhubert@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
